### PR TITLE
Confirmed Maestro initial number "6"

### PR DESCRIPTION
**Pull request by zedaraf**

### CODE REVIEW

**Comment by cholojuanito** [comment]
Do you have any links to show this?

**Comment by ziyadvf** [comment]
Try generating a random number:
https://ccard-generator.com/generate-card/maestro
Some example card numbers start with 6.

**Comment by cholojuanito** [comment]
Well [this Wikipedia article](https://en.wikipedia.org/wiki/Payment_card_number) doesn't have just "6" listed under the IIN's for Maestro.
I think the number's generated at your link follow the patterns above the commented out "6".

My worry is that just putting "6" down will return Maestro always instead of other potential card types. 

I think the best solution is to just remove that line, unless you can find some cases were typing out a full number doesn't show the correct card type.

**Comment by cholojuanito** [comment]
Or perhaps I need to implement a way to have multiple types be returned since a substring like "6" could be Discover, Maestro, etc.

**Comment by ziyadvf** [comment]
Alright, sounds great!

**Pull request closed without merging**
